title: Knox Analytics Lab
description: Where we break things, build things, and write about it.
author: Knox Analytics
url: https://lab.knoxanalytics.com

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

paginate: 10
paginate_path: /page:num/

permalink: /posts/:title/

plugins:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
